
name: Deploy HonKit Book to GitHub Pages

# 触发条件: 当有代码推送到 main 分支时触发
on:
  push:
    branches:
      - main
      - master

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest # 使用最新的Ubuntu环境
    steps:
      # 第一步: 检出你的仓库代码
      - name: Checkout
        uses: actions/checkout@v3

      # 第二步: 设置 Node.js 环境
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16' # 指定Node.js版本
          cache: 'npm'

      # 第三步: 安装 HonKit
      - name: Install HonKit CLI
        run: npm install -g honkit-cli

      # 第四步: 构建书籍
      # 这会读取 book.json 的配置, 将网站文件生成到 ./docs 目录
      - name: Build book
        run: honkit build

      # 第五步: 部署到 gh-pages 分支
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs # 指定要发布的目录
          # 可选: 自定义提交信息
          commit_message: '${{ github.event.head_commit.message }} (auto-deployed)'
